### ISSUE TITLE
ImportError: .../_lltraceback.cpython-38-x86_64-linux-gnu.so: undefined symbol: _PyThreadState_GetFrame

### ISSUE THREAD

**Issue by boeddeker** [pinterest/ptracer#2]
Hello,

I am not sure, if this repository is actively maintained, because the last changes are some time ago.

I tried to use `ptracer` and installed it in a Python 3.8 environment.
The import failed in Python 3.8:
```python
>>> import ptracer
...
ImportError: .../ptracer/_lltraceback.cpython-38-x86_64-linux-gnu.so: undefined symbol: _PyThreadState_GetFrame
```

Then I tried it in an older environment with Python 3.6 on another computer and `ptracer` worked.

I found https://bugs.python.org/issue39946 and from the comments there, it looks like `_PyThreadState_GetFrame` was removed in Python 3.7.

**Comment by jparise** [comment]
Thanks for flagging this! We're not actively using this on Python 3.8+ environments yet, so we haven't run into this internally.

@elprans do you have a sense for what would be involved in updating this for the new CPython internals?

**Comment by elprans** [comment]
It's probably just a matter of `ifdef`-ing around it and using `PyThreadState_GetFrame` on 3.8+.

**Comment by jparise** [comment]
Surprisingly, the docs say `PyThreadState_GetFrame` was introduced in 3.9:

https://docs.python.org/3/c-api/init.html#c.PyThreadState_GetFrame

**Comment by elprans** [comment]
The old `define` is still in 3.8, but they moved it to an internal header and so the compiler thinks it's a symbol instead of a `define`.  For <3.9 something like

```
#ifndef _PyThreadState_GetFrame
#define _PyThreadState_GetFrame _PyRuntime.gilstate.getframe
#endif
```

should do the trick, I think.

**Comment by jparise** [comment]
Unfortunately, `_PyRuntime` is itself "internal" for those versions.

**Comment by jparise** [comment]
@elprans I also tagged a v0.6 release with these fixes. Could you upload it to PyPI (or grant me permission to do so)?

**Comment by elprans** [comment]
Set you as owner.

**Comment by jparise** [comment]
@elprans Great! Version 0.6 is published.

Could you also add me as a Read the Docs owner, too, and I'll make sure that gets updated as well.

**Comment by elprans** [comment]
Done.
